import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Hearder from "./(root)/_components/Header";
import { Toaster } from "@/components/ui/toaster";
import ReactQueryProvider from "@/provider";

const interFont = Inter({ subsets: ["vietnamese"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head />
      <body className={`${interFont.className}`}>
        <ReactQueryProvider>
          <div>
            <ThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem
              disableTransitionOnChange
            >
              <Hearder />
              {children}
            </ThemeProvider>
            <Toaster />
          </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
